name = "do-simple-store"
type = "javascript"
account_id = ''
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{ name = "OBJECT", class_name = "Object" }]